name: camera_test
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  camera: ^0.10.5+2
  camerawesome: ^1.4.0
  flutter:
    sdk: flutter
  open_file: ^3.3.2
  video_player: ^2.7.0
  path_provider:
  path: ^1.8.2
  flutter_exif_rotation: ^0.5.1
  image_picker: ^1.0.2
  imageview360: ^1.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
